server:
  tomcat:
    max-threads: 500 # Maximum amount of worker threads.
    min-spare-threads: 50 # Minimum amount of worker threads

spring:
  redis:
    remote: false        #cachecloud 获取
    host: 192.168.10.74
    port: 6379
    database: 0
    password: redis0118
  rabbitmq:
    host: 192.168.10.73
    port: 5673
    username: mqadmin
    password: 123456
  http:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      
redis:
  cache:
    expiration: 3601

ribbon:
  eager-load:
    enabled: true #开启Ribbon的饥饿加载模式
    clients: sky-auth #指定需要饥饿加载的服务名
  Httpclient:
    enabled: false
  OkHttp:
    enabled: true
  ReadTimeout: 10000
  ConnectTimeout: 10000

feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      feignName:
        connectTimeout: 30000
        readTimeout: 30000
  compression:
    request:
      enabled: true
    response:
      enabled: true

hystrix:
  threadpool:
    default:
      coreSize: 500
      maxQueueSize: 1000
      queueSizeRejectionThreshold: 800
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000

#监控断点配置
management:
  security:
    enabled: false
endpoints:
  actuator:
    enabled: true
  shutdown:
    enabled: false

