server:
  port: 5003

# datasoure默认使用JDBC
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: sky
    password: sky123
    url: jdbc:mysql://localhost:3306/sky_base?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

zipkin:
  collector:
    rabbitmq:
      addresses: 192.168.10.73:5673
      password: 123456
      username: mqadmin
      queue: zipkin
  storage:
    type: mysql
