server:
  port: 3000

# datasoure默认使用JDBC
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: sky
    password: sky123
    url: jdbc:mysql://localhost:3306/sky_base?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false

