server:
  port: 4051

spring:
  datasource:
    dataSourceClassName: com.mysql.jdbc.Driver
    username: sky
    password: sky123
    url: jdbc:mysql://localhost:3306/sky_base?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
  
elasticJob:
  zk:
    serverLists: 140.143.198.198
    namespace: sky_job