server:
  port: 8007

# sleuth配置
spring:
  zipkin:
    rabbitmq:
      queue: zipkin
  sleuth:
    sampler:
      percentage: 0.2

# 分库分表支持
sharding:
  jdbc:
      datasource:
        names: ds_0,ds_1
        ds_0:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.jdbc.Driver
          username: sky
          password: sky123
          jdbc-url: jdbc:mysql://localhost:3306/sky_record0?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
        ds_1:
          type: com.zaxxer.hikari.HikariDataSource
          driver-class-name: com.mysql.jdbc.Driver
          username: sky
          password: sky123
          jdbc-url: jdbc:mysql://localhost:3306/sky_record1?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
      config:
        sharding:
          defaultDataSourceName: ds_1
          default-database-strategy:
            inline:
              sharding-column: maint_id
              algorithm-expression: ds_${(maint_id % 2)+0}
          tables:
            rr_repair_record:
              actualDataNodes: ds_${0..1}.rr_repair_record_${0..2}
              tableStrategy:
                inline:
                  shardingColumn: maint_id
                  algorithmExpression: rr_repair_record_${maint_id % 3}
            rr_repair_item:
              actualDataNodes: ds_${0..1}.rr_repair_item_${0..2}
              tableStrategy:
                inline:
                  shardingColumn: maint_id
                  algorithmExpression: rr_repair_item_${maint_id % 3}
            rr_repair_part:
              actualDataNodes: ds_${0..1}.rr_repair_part_${0..2}
              tableStrategy:
                inline:
                  shardingColumn: maint_id
                  algorithmExpression: rr_repair_part_${maint_id % 3}

#mybaits-plus配置，修改主键类型，mapper.xml、type 别名等
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  typeAliasesPackage: com.github.sky.recordService.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 1
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false              
